spring:
  rabbitmq:
    host: ${mq.app.rabbitmq.host}
    port: ${mq.app.rabbitmq.port}
    username: ${mq.app.rabbitmq.user}
    password: ${mq.app.rabbitmq.pass}

mq:
  app:
    rabbitmq:
      host: localhost
      port: 5672
      user: user
      pass: pass
      topic: topic1
      queue: queue1
